<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="alp22060" failures="4" tests="8" name="Test" time="3.822" errors="0" timestamp="2024-08-19T15:25:09 IST">
  <testcase classname="api.test.UserTests" name="testCreateUser1" time="1.294"/>
  <testcase classname="api.test.UserTests" name="testReadUser1" time="0.177"/>
  <testcase classname="api.test.UserTests" name="testCreateUser2" time="0.613"/>
  <testcase classname="api.test.UserTests" name="testReadUsers1and2" time="0.315">
    <failure type="java.lang.AssertionError" message="expected [Apple iPhone 12 Pro Max] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Apple iPhone 12 Pro Max] but found [null]
at api.test.UserTests.testReadUsers1and2(UserTests.java:126)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testReadUsers1and2 -->
  <testcase classname="api.test.UserTests" name="testUpdateUser2" time="0.247">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testUpdateUser2(UserTests.java:148)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUser2 -->
  <testcase classname="api.test.UserTests" name="testReadUser2" time="0.185">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testReadUser2(UserTests.java:170)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testReadUser2 -->
  <testcase classname="api.test.UserTests" name="testdeleteUser2" time="0.189">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testdeleteUser2(UserTests.java:186)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteUser2 -->
  <testcase classname="api.test.UserTests" name="testreaduser2afterdelete" time="0.185"/>
</testsuite> <!-- Test -->
